+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++SMAC+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------3s_vs_5z-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True exp_name="3S5Z-QMIX-B" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" exp_name="3S5Z-QMIX-N" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" exp_name="3S5Z-QMIX-N-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_n_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True exp_name="3S5Z-QMIX-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_da.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True exp_name="3S5Z-QMIX-DA-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_da_c.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="3S5Z-QMIX-TRANS-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="3S5Z-QMIX-TRANS-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="3S5Z-QMIX-TRANS-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="3S5Z-QMIX-TRANS-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="3S5Z-QMIX-TRANS-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="3S5Z-QMIX-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="3S5Z-QMIX-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True exp_name="3S5Z-QMIX-GRU-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True exp_name="3S5Z-QMIX-GRU-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True exp_name="3S5Z-QMIX-GRU-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True exp_name="3S5Z-QMIX-GRU-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True exp_name="3S5Z-QMIX-GRU-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True exp_name="3S5Z-QMIX-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True exp_name="3S5Z-QMIX-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '3s5z_test_qmix_gru_ms_h_student.log'


-------------------------------------------------------------5m_vs_6m-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True exp_name="5M6M-QMIX-B" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" exp_name="5M6M-QMIX-N" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" exp_name="5M6M-QMIX-N-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_n_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True exp_name="5M6M-QMIX-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_da.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True exp_name="5M6M-QMIX-DA-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_da_c.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="5M6M-QMIX-TRANS-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="5M6M-QMIX-TRANS-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="5M6M-QMIX-TRANS-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="5M6M-QMIX-TRANS-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="5M6M-QMIX-TRANS-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="5M6M-QMIX-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="5M6M-QMIX-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True exp_name="5M6M-QMIX-GRU-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True exp_name="5M6M-QMIX-GRU-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True exp_name="5M6M-QMIX-GRU-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True exp_name="5M6M-QMIX-GRU-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True exp_name="5M6M-QMIX-GRU-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True exp_name="5M6M-QMIX-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True exp_name="5M6M-QMIX-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '5m6m_test_qmix_gru_ms_h_student.log'


-------------------------------------------------------------6h_vs_8z-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="none" delay_aware=True exp_name="6H8Z-QMIX-B" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="none" exp_name="6H8Z-QMIX-N" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="none" exp_name="6H8Z-QMIX-N-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_n_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="none" delay_aware=True exp_name="6H8Z-QMIX-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_da.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="none" delay_aware=True exp_name="6H8Z-QMIX-DA-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_da_c.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="6H8Z-QMIX-TRANS-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" exp_name="6H8Z-QMIX-TRANS-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="6H8Z-QMIX-TRANS-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="6H8Z-QMIX-TRANS-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="6H8Z-QMIX-TRANS-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="6H8Z-QMIX-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True transformer_structure="encoder-decoder" use_history=True exp_name="6H8Z-QMIX-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True exp_name="6H8Z-QMIX-GRU-MS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ms_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True exp_name="6H8Z-QMIX-GRU-SS-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ss_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True use_history=True exp_name="6H8Z-QMIX-GRU-MS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ms_h_c.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True use_history=True exp_name="6H8Z-QMIX-GRU-SS-H-C" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ss_h_c.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True use_history=True exp_name="6H8Z-QMIX-GRU-SS-H-C-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ss_h_c_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="single_step" delay_aware=True use_history=True exp_name="6H8Z-QMIX-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z predictor_mode="multi_step" delay_aware=True use_history=True exp_name="6H8Z-QMIX-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' '6h8z_test_qmix_gru_ms_h_student.log'
