+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MPE+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------TAG-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_da.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" exp_name="TAG-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" use_history=True exp_name="TAG-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" use_history=True exp_name="TAG-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms_h_student.log'


-------------------------------------------------------------SPREAD-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_da.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" exp_name="SPREAD-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" use_history=True exp_name="SPREAD-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" use_history=True exp_name="SPREAD-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms_h_student.log'


-------------------------------------------------------------REFERENCE-------------------------------------------------------------
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_b.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_n.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_da.log'

#####transformer#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" exp_name="REFERENCE-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ms.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" use_history=True exp_name="REFERENCE-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ms_h.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss_student.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss_h_teacher.log'
sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ss_h_student.log'

sh ./test_uf.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" use_history=True exp_name="REFERENCE-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'reference_test_vdn_gru_ms_h_student.log'
