+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MPE+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------TAG-------------------------------------------------------------
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_b.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_n.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_da.log'

#####transformer#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="TAG-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="TAG-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" exp_name="TAG-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" use_history=True exp_name="TAG-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" exp_name="TAG-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" use_history=True exp_name="TAG-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" use_history=True exp_name="TAG-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'tag_test_vdn_gru_ms_h_student.log'


-------------------------------------------------------------SPREAD-------------------------------------------------------------
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_b.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_n.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_da.log'

#####transformer#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="SPREAD-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="SPREAD-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" exp_name="SPREAD-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" use_history=True exp_name="SPREAD-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" exp_name="SPREAD-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" use_history=True exp_name="SPREAD-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" use_history=True exp_name="SPREAD-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path=""' 'spread_test_vdn_gru_ms_h_student.log'


-------------------------------------------------------------REFERENCE-------------------------------------------------------------
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-B" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-B_2025-04-08 11_11_50.561405_pd_vdn_seed985676314"' 'reference_test_vdn_b.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-N" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-DA_2025-04-08 11_12_48.973077_pd_vdn_seed985676314"' 'reference_test_vdn_n.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" exp_name="REFERENCE-VDN-DA" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-N_2025-04-08 16_14_42.552180_pd_vdn_seed985676314"' 'reference_test_vdn_da.log'

#####transformer#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-MS" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-MS_2025-04-08 16_14_55.289960_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS_2025-04-08 16_15_09.174799_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-MS-H" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-MS-H_2025-04-08 16_15_30.583638_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS-H_2025-04-08 16_15_54.166427_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS-TEACHER_2025-04-16 01_19_07.863078_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" exp_name="REFERENCE-VDN-TRANS-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS-STUDENT_2025-04-16 16_38_45.715691_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS-H-TEACHER_2025-04-08 16_17_16.485207_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-SS-H-STUDENT_2025-04-09 22_35_54.875527_pd_vdn_seed985676314"' 'reference_test_vdn_trans_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" use_history=True exp_name="REFERENCE-VDN-TRANS-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-TRANS-MS-H-STUDENT_2025-04-22 20_49_53.632219_pd_vdn_seed671416054"' 'reference_test_vdn_trans_ms_h_student.log'

#####gru#####
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" exp_name="REFERENCE-VDN-GRU-MS" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-MS_2025-04-09 09_37_30.323984_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ms.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS_2025-04-09 09_37_43.920328_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" use_history=True exp_name="REFERENCE-VDN-GRU-MS-H" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-MS-H_2025-04-09 09_37_57.176358_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ms_h.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS-H_2025-04-09 09_38_28.883344_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss_h.log'
# teacher-student
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS-TEACHER_2025-04-16 01_19_22.026763_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" exp_name="REFERENCE-VDN-GRU-SS-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS-STUDENT_2025-04-16 16_38_50.206108_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss_student.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H-TEACHER" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS-H-TEACHER_2025-04-09 09_38_52.019286_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss_h_teacher.log'
sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" use_history=True exp_name="REFERENCE-VDN-GRU-SS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-SS-H-STUDENT_2025-04-09 22_36_47.135315_pd_vdn_seed985676314"' 'reference_test_vdn_gru_ss_h_student.log'

sh ./test_f.sh 'CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" use_history=True exp_name="REFERENCE-VDN-GRU-MS-H-STUDENT" test_nepisode=1280 evaluate=True checkpoint_path="/fusongchen/cds/pymarl3-delayed/test_models/REFERENCE/REFERENCE-VDN-GRU-MS-H-STUDENT_2025-04-22 20_50_20.897539_pd_vdn_seed671416054"' 'reference_test_vdn_gru_ms_h_student.log'
