+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++SMAC+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------3s_vs_5z-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="3S5Z-VDN-B" >> 3s5z_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" exp_name="3S5Z-VDN-N" >> 3s5z_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" cheating_start_value=1.0 exp_name="3S5Z-VDN-N-C" >> 3s5z_vdn_n_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-VDN-TRANS-MS-C" >> 3s5z_vdn_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-VDN-TRANS-SS-C" >> 3s5z_vdn_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-VDN-TRANS-MS-H-C" >> 3s5z_vdn_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-VDN-TRANS-SS-H-C" >> 3s5z_vdn_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-VDN-TRANS-SS-H-C-TEACHER" >> 3s5z_vdn_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-VDN-TRANS-SS-H-STUDENT" >> 3s5z_vdn_trans_ss_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-VDN-GRU-MS-C" >> 3s5z_vdn_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-VDN-GRU-SS-C" >> 3s5z_vdn_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-VDN-GRU-MS-H-C" >> 3s5z_vdn_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-VDN-GRU-SS-H-C" >> 3s5z_vdn_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-VDN-GRU-SS-H-C-TEACHER" >> 3s5z_vdn_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-VDN-GRU-SS-H-STUDENT" >> 3s5z_vdn_gru_ss_h_student.log 2>&1 &


-------------------------------------------------------------5m_vs_6m-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="5M6M-VDN-B" >> 5m6m_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" exp_name="5M6M-VDN-N" >> 5m6m_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" cheating_start_value=1.0 exp_name="5M6M-VDN-N-C" >> 5m6m_vdn_n_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-VDN-TRANS-MS-C" >> 5m6m_vdn_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-VDN-TRANS-SS-C" >> 5m6m_vdn_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-VDN-TRANS-MS-H-C" >> 5m6m_vdn_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-VDN-TRANS-SS-H-C" >> 5m6m_vdn_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-VDN-TRANS-SS-H-C-TEACHER" >> 5m6m_vdn_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-VDN-TRANS-SS-H-STUDENT" >> 5m6m_vdn_trans_ss_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-VDN-GRU-MS-C" >> 5m6m_vdn_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-VDN-GRU-SS-C" >> 5m6m_vdn_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-VDN-GRU-MS-H-C" >> 5m6m_vdn_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-VDN-GRU-SS-H-C" >> 5m6m_vdn_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-VDN-GRU-SS-H-C-TEACHER" >> 5m6m_vdn_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-VDN-GRU-SS-H-STUDENT" >> 5m6m_vdn_gru_ss_h_student.log 2>&1 &


-------------------------------------------------------------6h_vs_8z-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="6H8Z-VDN-B" >> 6h8z_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" exp_name="6H8Z-VDN-N" >> 6h8z_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" cheating_start_value=1.0 exp_name="6H8Z-VDN-N-C" >> 6h8z_vdn_n_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-VDN-TRANS-MS-C" >> 6h8z_vdn_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-VDN-TRANS-SS-C" >> 6h8z_vdn_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-VDN-TRANS-MS-H-C" >> 6h8z_vdn_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=8 transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-VDN-TRANS-SS-H-C" >> 6h8z_vdn_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=5000000 t_max=10050000 exp_name="6H8Z-VDN-TRANS-SS-H-C-TEACHER" >> 6h8z_vdn_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=8 transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-VDN-TRANS-SS-H-STUDENT" >> 6h8z_vdn_trans_ss_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-VDN-GRU-MS-C" >> 6h8z_vdn_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-VDN-GRU-SS-C" >> 6h8z_vdn_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-VDN-GRU-MS-H-C" >> 6h8z_vdn_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-VDN-GRU-SS-H-C" >> 6h8z_vdn_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 cheating_start_time=2000000 cheating_end_time=5000000 t_max=10050000 exp_name="6H8Z-VDN-GRU-SS-H-C-TEACHER" >> 6h8z_vdn_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-VDN-GRU-SS-H-STUDENT" >> 6h8z_vdn_gru_ss_h_student.log 2>&1 &
