+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MPE+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------TAG-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="TAG-VDN-B" >> tag_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" exp_name="TAG-VDN-N" >> tag_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="none" delay_aware=True exp_name="TAG-VDN-DA" >> tag_vdn_da.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="TAG-VDN-TRANS-MS" >> tag_vdn_trans_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="TAG-VDN-TRANS-SS" >> tag_vdn_trans_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True exp_name="TAG-VDN-TRANS-MS-H" >> tag_vdn_trans_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True exp_name="TAG-VDN-TRANS-SS-H" >> tag_vdn_trans_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-TRANS-SS-TEACHER" >> tag_vdn_trans_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-TRANS-SS-STUDENT" >> tag_vdn_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-TRANS-SS-H-TEACHER" >> tag_vdn_trans_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-TRANS-SS-H-STUDENT" >> tag_vdn_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-TRANS-MS-H-TEACHER" >> tag_vdn_trans_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-TRANS-MS-H-STUDENT" >> tag_vdn_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True exp_name="TAG-VDN-GRU-MS" >> tag_vdn_gru_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True exp_name="TAG-VDN-GRU-SS" >> tag_vdn_gru_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True use_history=True exp_name="TAG-VDN-GRU-MS-H" >> tag_vdn_gru_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True use_history=True exp_name="TAG-VDN-GRU-SS-H" >> tag_vdn_gru_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-GRU-SS-TEACHER" >> tag_vdn_gru_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-GRU-SS-STUDENT" >> tag_vdn_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-GRU-SS-H-TEACHER" >> tag_vdn_gru_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-GRU-SS-H-STUDENT" >> tag_vdn_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="TAG-VDN-GRU-MS-H-TEACHER" >> tag_vdn_gru_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-tag-v3" env_args.pretrained_wrapper="PretrainedTag" predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="TAG-VDN-GRU-MS-H-STUDENT" >> tag_vdn_gru_ms_h_student.log 2>&1 &


-------------------------------------------------------------SPREAD-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="SPREAD-VDN-B" >> spread_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" exp_name="SPREAD-VDN-N" >> spread_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="none" delay_aware=True exp_name="SPREAD-VDN-DA" >> spread_vdn_da.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="SPREAD-VDN-TRANS-MS" >> spread_vdn_trans_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True exp_name="SPREAD-VDN-TRANS-SS" >> spread_vdn_trans_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True exp_name="SPREAD-VDN-TRANS-MS-H" >> spread_vdn_trans_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True exp_name="SPREAD-VDN-TRANS-SS-H" >> spread_vdn_trans_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-TRANS-SS-TEACHER" >> spread_vdn_trans_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-TRANS-SS-STUDENT" >> spread_vdn_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-TRANS-SS-H-TEACHER" >> spread_vdn_trans_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-TRANS-SS-H-STUDENT" >> spread_vdn_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-TRANS-MS-H-TEACHER" >> spread_vdn_trans_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-TRANS-MS-H-STUDENT" >> spread_vdn_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True exp_name="SPREAD-VDN-GRU-MS" >> spread_vdn_gru_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True exp_name="SPREAD-VDN-GRU-SS" >> spread_vdn_gru_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True use_history=True exp_name="SPREAD-VDN-GRU-MS-H" >> spread_vdn_gru_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True use_history=True exp_name="SPREAD-VDN-GRU-SS-H" >> spread_vdn_gru_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-GRU-SS-TEACHER" >> spread_vdn_gru_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-GRU-SS-STUDENT" >> spread_vdn_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-GRU-SS-H-TEACHER" >> spread_vdn_gru_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-GRU-SS-H-STUDENT" >> spread_vdn_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="SPREAD-VDN-GRU-MS-H-TEACHER" >> spread_vdn_gru_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-spread-v3" predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="SPREAD-VDN-GRU-MS-H-STUDENT" >> spread_vdn_gru_ms_h_student.log 2>&1 &


-------------------------------------------------------------REFERENCE-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 t_max=10050000 exp_name="REFERENCE-VDN-B" >> reference_vdn_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" t_max=10050000 exp_name="REFERENCE-VDN-N" >> reference_vdn_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="none" delay_aware=True t_max=10050000 exp_name="REFERENCE-VDN-DA" >> reference_vdn_da.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True t_max=10050000 exp_name="REFERENCE-VDN-TRANS-MS" >> reference_vdn_trans_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS" >> reference_vdn_trans_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True t_max=10050000 exp_name="REFERENCE-VDN-TRANS-MS-H" >> reference_vdn_trans_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS-H" >> reference_vdn_trans_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS-TEACHER" >> reference_vdn_trans_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS-STUDENT" >> reference_vdn_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS-H-TEACHER" >> reference_vdn_trans_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-TRANS-SS-H-STUDENT" >> reference_vdn_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-TRANS-MS-H-TEACHER" >> reference_vdn_trans_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_tf4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-TRANS-MS-H-STUDENT" >> reference_vdn_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True t_max=10050000 exp_name="REFERENCE-VDN-GRU-MS" >> reference_vdn_gru_ms.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS" >> reference_vdn_gru_ss.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True t_max=10050000 exp_name="REFERENCE-VDN-GRU-MS-H" >> reference_vdn_gru_ms_h.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS-H" >> reference_vdn_gru_ss_h.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS-TEACHER" >> reference_vdn_gru_ss_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS-STUDENT" >> reference_vdn_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS-H-TEACHER" >> reference_vdn_gru_ss_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-GRU-SS-H-STUDENT" >> reference_vdn_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 t_max=10050000 exp_name="REFERENCE-VDN-GRU-MS-H-TEACHER" >> reference_vdn_gru_ms_h_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_vdn_gru4mpe --env-config=gymma with env_args.key="pz-mpe-simple-reference-v3" predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_student_start_time=3000000 teacher_student_end_time=7000000 teacher_model_dir="" t_max=10050000 exp_name="REFERENCE-VDN-GRU-MS-H-STUDENT" >> reference_vdn_gru_ms_h_student.log 2>&1 &
