+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++SMAC+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-------------------------------------------------------------3s_vs_5z-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="3S5Z-QMIX-B" >> 3s5z_qmix_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" exp_name="3S5Z-QMIX-N" >> 3s5z_qmix_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" cheating_start_value=1.0 exp_name="3S5Z-QMIX-N-C" >> 3s5z_qmix_n_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True exp_name="3S5Z-QMIX-DA" >> 3s5z_qmix_da.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="none" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-DA-C" >> 3s5z_qmix_da_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-TRANS-MS-C" >> 3s5z_qmix_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-TRANS-SS-C" >> 3s5z_qmix_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-TRANS-MS-H-C" >> 3s5z_qmix_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-TRANS-SS-H-C" >> 3s5z_qmix_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=2 transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-TRANS-SS-C-TEACHER" >> 3s5z_qmix_trans_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=2 transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-TRANS-SS-STUDENT" >> 3s5z_qmix_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-TRANS-SS-H-C-TEACHER" >> 3s5z_qmix_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-TRANS-SS-H-STUDENT" >> 3s5z_qmix_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-TRANS-MS-H-C-TEACHER" >> 3s5z_qmix_trans_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-TRANS-MS-H-STUDENT" >> 3s5z_qmix_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-GRU-MS-C" >> 3s5z_qmix_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-GRU-SS-C" >> 3s5z_qmix_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-GRU-MS-H-C" >> 3s5z_qmix_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="3S5Z-QMIX-GRU-SS-H-C" >> 3s5z_qmix_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-GRU-SS-C-TEACHER" >> 3s5z_qmix_gru_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-GRU-SS-STUDENT" >> 3s5z_qmix_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-GRU-SS-H-C-TEACHER" >> 3s5z_qmix_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-GRU-SS-H-STUDENT" >> 3s5z_qmix_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="3S5Z-QMIX-GRU-MS-H-C-TEACHER" >> 3s5z_qmix_gru_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=3s_vs_5z predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="3S5Z-QMIX-GRU-MS-H-STUDENT" >> 3s5z_qmix_gru_ms_h_student.log 2>&1 &


-------------------------------------------------------------5m_vs_6m-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="5M6M-QMIX-B" >> 5m6m_qmix_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" exp_name="5M6M-QMIX-N" >> 5m6m_qmix_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" cheating_start_value=1.0 exp_name="5M6M-QMIX-N-C" >> 5m6m_qmix_n_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True exp_name="5M6M-QMIX-DA" >> 5m6m_qmix_da.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="none" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-QMIX-DA-C" >> 5m6m_qmix_da_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-QMIX-TRANS-MS-C" >> 5m6m_qmix_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-QMIX-TRANS-SS-C" >> 5m6m_qmix_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-QMIX-TRANS-MS-H-C" >> 5m6m_qmix_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-QMIX-TRANS-SS-H-C" >> 5m6m_qmix_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-TRANS-SS-C-TEACHER" >> 5m6m_qmix_trans_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-TRANS-SS-STUDENT" >> 5m6m_qmix_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-TRANS-SS-H-C-TEACHER" >> 5m6m_qmix_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-TRANS-SS-H-STUDENT" >> 5m6m_qmix_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-TRANS-MS-H-C-TEACHER" >> 5m6m_qmix_trans_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-TRANS-MS-H-STUDENT" >> 5m6m_qmix_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-QMIX-GRU-MS-C" >> 5m6m_qmix_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="5M6M-QMIX-GRU-SS-C" >> 5m6m_qmix_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-QMIX-GRU-MS-H-C" >> 5m6m_qmix_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="5M6M-QMIX-GRU-SS-H-C" >> 5m6m_qmix_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-GRU-SS-C-TEACHER" >> 5m6m_qmix_gru_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-GRU-SS-STUDENT" >> 5m6m_qmix_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-GRU-SS-H-C-TEACHER" >> 5m6m_qmix_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-GRU-SS-H-STUDENT" >> 5m6m_qmix_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="5M6M-QMIX-GRU-MS-H-C-TEACHER" >> 5m6m_qmix_gru_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=5m_vs_6m predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="5M6M-QMIX-GRU-MS-H-STUDENT" >> 5m6m_qmix_gru_ms_h_student.log 2>&1 &


-------------------------------------------------------------6h_vs_8z-------------------------------------------------------------
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" delay_aware=True cheating_start_value=1.0 cheating_end_value=1.0 exp_name="6H8Z-QMIX-B" >> 6h8z_qmix_b.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" exp_name="6H8Z-QMIX-N" >> 6h8z_qmix_n.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" cheating_start_value=1.0 exp_name="6H8Z-QMIX-N-C" >> 6h8z_qmix_n_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" delay_aware=True exp_name="6H8Z-QMIX-DA" >> 6h8z_qmix_da.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="none" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-DA-C" >> 6h8z_qmix_da_c.log 2>&1 &

#####transformer#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-TRANS-MS-C" >> 6h8z_qmix_trans_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-TRANS-SS-C" >> 6h8z_qmix_trans_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-TRANS-MS-H-C" >> 6h8z_qmix_trans_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=8 transformer_structure="encoder-decoder" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-TRANS-SS-H-C" >> 6h8z_qmix_trans_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-TRANS-SS-C-TEACHER" >> 6h8z_qmix_trans_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=8 transformer_structure="encoder-decoder" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-TRANS-SS-STUDENT" >> 6h8z_qmix_trans_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=4 transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-TRANS-SS-H-C-TEACHER" >> 6h8z_qmix_trans_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" num_minibatch_predictor=8 transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-TRANS-SS-H-STUDENT" >> 6h8z_qmix_trans_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-TRANS-MS-H-C-TEACHER" >> 6h8z_qmix_trans_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_tf4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" transformer_structure="encoder-decoder" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-TRANS-MS-H-STUDENT" >> 6h8z_qmix_trans_ms_h_student.log 2>&1 &

#####gru#####
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-GRU-MS-C" >> 6h8z_qmix_gru_ms_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-GRU-SS-C" >> 6h8z_qmix_gru_ss_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-GRU-MS-H-C" >> 6h8z_qmix_gru_ms_h_c.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True cheating_start_value=1.0 exp_name="6H8Z-QMIX-GRU-SS-H-C" >> 6h8z_qmix_gru_ss_h_c.log 2>&1 &
# teacher-student
CUDA_VISIBLE_DEVICES="0" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-GRU-SS-C-TEACHER" >> 6h8z_qmix_gru_ss_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="1" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-GRU-SS-STUDENT" >> 6h8z_qmix_gru_ss_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-GRU-SS-H-C-TEACHER" >> 6h8z_qmix_gru_ss_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="3" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="single_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-GRU-SS-H-STUDENT" >> 6h8z_qmix_gru_ss_h_student.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True use_history=True delay_value=2 delay_scope=1 n_expand_action=3 cheating_start_value=1.0 t_max=10050000 exp_name="6H8Z-QMIX-GRU-MS-H-C-TEACHER" >> 6h8z_qmix_gru_ms_h_c_teacher.log 2>&1 &
CUDA_VISIBLE_DEVICES="2" nohup python -u src/main.py --config=pd_qmix_gru4sc2 --env-config=sc2 with env_args.map_name=6h_vs_8z epsilon_anneal_time=500000 td_lambda=0.3 predictor_mode="multi_step" delay_aware=True use_history=True teacher_student_start_value=0.5 teacher_student_end_value=0.1 teacher_model_dir="" exp_name="6H8Z-QMIX-GRU-MS-H-STUDENT" >> 6h8z_qmix_gru_ms_h_student.log 2>&1 &
